name: Site Generierung und Push

on:
  push:
    branches:
    - 'master'

jobs:
  deploy:
    name: deploy on github
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 13
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '13'
    - name: Deploy to Github Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/${GITHUB_REPOSITORY}.git
        cd `ls -d */`
        rm -rf docs/*
        chmod +x ./mvnw
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        ./mvnw
        git config --global user.email "huluvu424242@gmail.com"
        git config --global user.name "${GITHUB_REPOSITORY_OWNER}"
        git remote set-url --push origin https://OWNER:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add docs/*
        git commit -am "neue Doku generiert"
        git push


